# Generated by Django 3.2 on 2021-04-13 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SearchEngineModel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dictionary',
            old_name='document_id',
            new_name='document',
        ),
    ]
