# Generated by Django 3.2 on 2021-04-13 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SearchEngineModel', '0002_rename_document_id_dictionary_document'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dictionary',
            unique_together={('word', 'document_id')},
        ),
    ]
