# Generated by Django 3.2 on 2021-04-14 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SearchEngineModel', '0004_rename_name_document_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
